package com.yryj.model;

import com.google.code.morphia.annotations.Id;
import com.google.code.morphia.annotations.Indexed;
import com.google.code.morphia.utils.IndexDirection;

// Generated 2016-4-26 12:25:28 by Hibernate Tools 4.0.0

/**
 * Chapter generated by hbm2java
 */
public class Chapter implements java.io.Serializable {
	@Id
	@Indexed(value=IndexDirection.ASC, name="id", unique=true, dropDups=true) 
    private long id;
	
	private long parentId;
	private long leftStory;
	private long level;   //第几层
	private long zan;     //点赞数
	private String userName;
	private String content;
	private boolean isEnd;
	private long viewNum;
	private String key;
	private String style;
	private String format;
	private long length;    //length: 0为短篇,1为中篇,2为长篇
	private long date;
	
	public Chapter() {
		 parentId=-1;
		 leftStory=0;
		 level=1;
		 zan=0;
		 userName="";
		 content="";
		 isEnd=false;
		 viewNum=0;
		 key="";
		 style="";
		 format="";
		 length=0;
		 date=System.currentTimeMillis();
	}
	
	public Chapter(long id,long parentId,long leftStory,long level,long zan,String userName,String content,boolean isEnd,long viewNum,String key,long length,long date){
		this.id=id;
		this.parentId=parentId;
		this.leftStory=leftStory;
		this.level=level;
		this.zan=zan;
		this.userName=userName;
		this.content=content;
		this.isEnd=isEnd;
		this.viewNum=viewNum;
		this.key=key;
		this.length=length;
		this.date=date;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getParentId() {
		return parentId;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}
	
	public long getLeftStory() {
		return leftStory;
	}

	public void setLeftStory(long leftStory) {
		this.leftStory = leftStory;
	}


	public long getLevel() {
		return level;
	}

	public void setLevel(long level) {
		this.level = level;
	}

	public long getZan() {
		return zan;
	}

	public void setZan(long zan) {
		this.zan = zan;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public boolean isEnd() {
		return isEnd;
	}

	public void setEnd(boolean isEnd) {
		this.isEnd = isEnd;
	}

	public long getViewNum() {
		return viewNum;
	}

	public void setViewNum(long viewNum) {
		this.viewNum = viewNum;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getStyle() {
		return style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public String getFormat() {
		return format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public long getLength() {
		return length;
	}

	public void setLength(long length) {
		this.length = length;
	}

	public long getDate() {
		return date;
	}

	public void setDate(long date) {
		this.date = date;
	}
	
	public String toString(){
		return "#id="+this.id
				+";parentId="+this.parentId
				+";leftStory="+this.leftStory
				+";level="+this.level
				+";zan="+this.zan
				+";userName="+this.userName
				+";content="+this.content
				+";isEnd="+this.isEnd
				+";viewNum="+this.viewNum
				+";key="+this.key
				+";length="+this.length
				+";date="+this.date;
	}
}
