package com.yryj.model;

// Generated 2016-4-21 11:17:52 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Chapter generated by hbm2java
 */
public class Chapter implements java.io.Serializable {

	private Integer id;
	private Chapter chapter;
	private User user;
	private int praise;
	private String content;
	private boolean isEnd;
	private Integer viewNum;
	private String key;
	private Set drafts = new HashSet(0);
	private Set utcs = new HashSet(0);
	private Set orders = new HashSet(0);
	private Set chapters = new HashSet(0);
	private Set stories = new HashSet(0);

	public Chapter() {
	}

	public Chapter(int praise, String content, boolean isEnd) {
		this.praise = praise;
		this.content = content;
		this.isEnd = isEnd;
	}

	public Chapter(Chapter chapter, User user, int praise, String content,
			boolean isEnd, Integer viewNum, String key, Set drafts, Set utcs,
			Set orders, Set chapters, Set stories) {
		this.chapter = chapter;
		this.user = user;
		this.praise = praise;
		this.content = content;
		this.isEnd = isEnd;
		this.viewNum = viewNum;
		this.key = key;
		this.drafts = drafts;
		this.utcs = utcs;
		this.orders = orders;
		this.chapters = chapters;
		this.stories = stories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Chapter getChapter() {
		return this.chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getPraise() {
		return this.praise;
	}

	public void setPraise(int praise) {
		this.praise = praise;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public boolean isIsEnd() {
		return this.isEnd;
	}

	public void setIsEnd(boolean isEnd) {
		this.isEnd = isEnd;
	}

	public Integer getViewNum() {
		return this.viewNum;
	}

	public void setViewNum(Integer viewNum) {
		this.viewNum = viewNum;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public Set getDrafts() {
		return this.drafts;
	}

	public void setDrafts(Set drafts) {
		this.drafts = drafts;
	}

	public Set getUtcs() {
		return this.utcs;
	}

	public void setUtcs(Set utcs) {
		this.utcs = utcs;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

	public Set getChapters() {
		return this.chapters;
	}

	public void setChapters(Set chapters) {
		this.chapters = chapters;
	}

	public Set getStories() {
		return this.stories;
	}

	public void setStories(Set stories) {
		this.stories = stories;
	}

}
