package com.yryj.model;

import com.google.code.morphia.annotations.Id;

// Generated 2016-4-26 12:25:28 by Hibernate Tools 4.0.0

/**
 * Chapter generated by hbm2java
 */
public class Chapter implements java.io.Serializable {
	@Id
    private long id;
	
	private int parentId;
	private int zan;
	private String userName;
	private String content;
	private boolean isEnd;
	private int viewNum;
	private String key;
	private String style;
	private String format;
	private String length;
	private long date;
	
	public Chapter() {
		 parentId=-1;
		 zan=0;
		 userName="";
		 content="";
		 isEnd=false;
		 viewNum=0;
		 key="";
		 style="";
		 format="";
		 length="";
		 date=System.currentTimeMillis();
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getParentId() {
		return parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public int getZan() {
		return zan;
	}

	public void setZan(int zan) {
		this.zan = zan;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public boolean isEnd() {
		return isEnd;
	}

	public void setEnd(boolean isEnd) {
		this.isEnd = isEnd;
	}

	public int getViewNum() {
		return viewNum;
	}

	public void setViewNum(int viewNum) {
		this.viewNum = viewNum;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getStyle() {
		return style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public String getFormat() {
		return format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public String getLength() {
		return length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	public long getDate() {
		return date;
	}

	public void setDate(long date) {
		this.date = date;
	}
}
