package com.yryj.model;

import com.google.code.morphia.annotations.Id;
import com.google.code.morphia.annotations.Indexed;
import com.google.code.morphia.utils.IndexDirection;

// Generated 2016-4-26 12:25:28 by Hibernate Tools 4.0.0

/**
 * Draft generated by hbm2java
 */
public class Draft implements java.io.Serializable {
	@Id
	@Indexed(value=IndexDirection.ASC, name="id", unique=true, dropDups=true) 
	private long id;
	
	private long userId;
	private long parentId;
	private String content;

	public Draft() {
		content="";
		parentId=-1;
		userId=-1;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public long getParentId() {
		return parentId;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	

}
