package com.yryj.model;

// Generated 2016-4-26 12:25:28 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private Chapter chapter;
	private User user;
	private int maxPrice;
	private Date endTime;

	public Order() {
	}

	public Order(Chapter chapter, User user, int maxPrice, Date endTime) {
		this.chapter = chapter;
		this.user = user;
		this.maxPrice = maxPrice;
		this.endTime = endTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Chapter getChapter() {
		return this.chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getMaxPrice() {
		return this.maxPrice;
	}

	public void setMaxPrice(int maxPrice) {
		this.maxPrice = maxPrice;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
