package com.yryj.model;

// Generated 2016-4-26 12:25:28 by Hibernate Tools 4.0.0

import com.google.code.morphia.annotations.Id;
import com.google.code.morphia.annotations.Indexed;
import com.google.code.morphia.utils.IndexDirection;

/**
 * Type generated by hbm2java
 */
public class Relations implements java.io.Serializable {
	@Id
	@Indexed(value=IndexDirection.ASC, name="id", unique=true, dropDups=true) 
	private long id;
	
	private long uId;  //用户id
	
	private String i2u; //喜欢的用户
	private String u2i;//关注我的人
	private String u2cZan; //喜欢的作品(点赞)
	private String u2cStore;//收藏的作品
	
	
	public Relations(){
		i2u="";
		u2i="";
		u2cZan="";
		u2cStore="";
	}


	public long getId() {
		return id;
	}


	public void setId(long id) {
		this.id = id;
	}


	public long getuId() {
		return uId;
	}


	public void setuId(long uId) {
		this.uId = uId;
	}


	public String getI2u() {
		return i2u;
	}


	public void setI2u(String i2u) {
		this.i2u = i2u;
	}


	public String getU2i() {
		return u2i;
	}


	public void setU2i(String u2i) {
		this.u2i = u2i;
	}


	public String getU2cZan() {
		return u2cZan;
	}


	public void setU2cZan(String u2cZan) {
		this.u2cZan = u2cZan;
	}


	public String getU2cStore() {
		return u2cStore;
	}


	public void setU2cStore(String u2cStore) {
		this.u2cStore = u2cStore;
	}
	
	
	
	
}
