package com.yryj.model;

// Generated 2016-4-26 12:25:28 by Hibernate Tools 4.0.0

/**
 * Style generated by hbm2java
 */
public class Style implements java.io.Serializable {

	private Integer id;
	private String style;

	public Style() {
	}

	public Style(String style) {
		this.style = style;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

}
