package com.yryj.model;

// Generated 2016-4-21 8:56:52 by Hibernate Tools 4.0.0

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private Integer id;
	private String type;

	public Type() {
	}

	public Type(String type) {
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
