package com.yryj.model;

// Generated 2016-4-9 12:39:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private Integer id;
	private String type;
	private Set stories = new HashSet(0);

	public Type() {
	}

	public Type(String type) {
		this.type = type;
	}

	public Type(String type, Set stories) {
		this.type = type;
		this.stories = stories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getStories() {
		return this.stories;
	}

	public void setStories(Set stories) {
		this.stories = stories;
	}

}
