package com.yryj.model;

// Generated 2016-4-21 11:17:52 by Hibernate Tools 4.0.0

/**
 * Utc generated by hbm2java
 */
public class Utc implements java.io.Serializable {

	private UtcId id;
	private Chapter chapter;
	private User user;

	public Utc() {
	}

	public Utc(UtcId id, Chapter chapter, User user) {
		this.id = id;
		this.chapter = chapter;
		this.user = user;
	}

	public UtcId getId() {
		return this.id;
	}

	public void setId(UtcId id) {
		this.id = id;
	}

	public Chapter getChapter() {
		return this.chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
