package com.yryj.model;

// Generated 2016-4-9 12:39:49 by Hibernate Tools 4.0.0

/**
 * UtcId generated by hbm2java
 */
public class UtcId implements java.io.Serializable {

	private int uid;
	private int chapterId;

	public UtcId() {
	}

	public UtcId(int uid, int chapterId) {
		this.uid = uid;
		this.chapterId = chapterId;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getChapterId() {
		return this.chapterId;
	}

	public void setChapterId(int chapterId) {
		this.chapterId = chapterId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtcId))
			return false;
		UtcId castOther = (UtcId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getChapterId() == castOther.getChapterId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getChapterId();
		return result;
	}

}
