package com.yryj.model;

// Generated 2016-4-26 12:25:28 by Hibernate Tools 4.0.0

/**
 * Utu generated by hbm2java
 */
public class Utu implements java.io.Serializable {

	private UtuId id;
	private User userByFanId;
	private User userByUid;

	public Utu() {
	}

	public Utu(UtuId id, User userByFanId, User userByUid) {
		this.id = id;
		this.userByFanId = userByFanId;
		this.userByUid = userByUid;
	}

	public UtuId getId() {
		return this.id;
	}

	public void setId(UtuId id) {
		this.id = id;
	}

	public User getUserByFanId() {
		return this.userByFanId;
	}

	public void setUserByFanId(User userByFanId) {
		this.userByFanId = userByFanId;
	}

	public User getUserByUid() {
		return this.userByUid;
	}

	public void setUserByUid(User userByUid) {
		this.userByUid = userByUid;
	}

}
