package com.yryj.model;

// Generated 2016-4-9 12:39:49 by Hibernate Tools 4.0.0

/**
 * UtuId generated by hbm2java
 */
public class UtuId implements java.io.Serializable {

	private int uid;
	private int fanId;

	public UtuId() {
	}

	public UtuId(int uid, int fanId) {
		this.uid = uid;
		this.fanId = fanId;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getFanId() {
		return this.fanId;
	}

	public void setFanId(int fanId) {
		this.fanId = fanId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtuId))
			return false;
		UtuId castOther = (UtuId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getFanId() == castOther.getFanId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getFanId();
		return result;
	}

}
